# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Catchphrase' do

pod 'AFNetworking', '~> 2.3'
pod 'SDWebImage', '~> 3.6'

end
